name: main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://p575768.mittwaldserver.info/  
          ftp-username: p575768
          ftp-password: ${{ secrets.ftp_password }}
